spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/studentdb
    cassandra:
      contact-points:
      - localhost
      port: 9042
      keyspace-name: rxjava
      username: 
      password: 
      
server:
  port: 8081
